Cache common/common_linux.Virtualization()
shirou/gopsutil pull request #942
Opened 2020-09-11 07:41 UTC by AtakanColak

By assuming virtualization environment won't change during a the program's runtime, we can cache common/common_linux.Virtualization() with a simple map to reduce amount of system calls. I first mentioned this issue at [890](https://github.com/shirou/gopsutil/pull/890#issuecomment-690211919)

2020-09-11 12:26 UTC, AtakanColak commented
I wanted to compare profiling results of this optimization. 

Before optimization of Virtualization(), there is a distinct compute weight on fillFromStatWithContext which calls Virtualization()

![image](https://user-images.githubusercontent.com/22523757/92925042-94d18780-f442-11ea-9e27-67e8a51deca4.png)

After optimization, we can clearly see that the compute weight is reduced and spread to the other functions. 

![image](https://user-images.githubusercontent.com/22523757/92924965-6eabe780-f442-11ea-9766-879a475e4cc5.png)

2020-09-11 12:45 UTC, shirou commented
I think these kind of optimization should be implemented in Application side, not library side.

2020-09-11 12:55 UTC, AtakanColak commented
@shirou could you elaborate on that? Most of the compute is spent with ReadLines on Virtualization which is in internal/common package. How could we optimize it from application side?

2020-09-11 13:58 UTC, shirou commented
```
package main

import (
        "fmt"
        "github.com/shirou/gopsutil/host"
)

var (
        h = ""
        g = ""
)

func main() {
        if h == "" {
                h, g, _ := host.Virtualization()
                fmt.Println(h, g)
        } else {
                fmt.Println(h, g)
        }
}
```
or whatever, in your application.

2020-09-11 14:28 UTC, AtakanColak commented
@shirou thank you for your reply. However your answer would be the case if it was my app who was calling Virtualization information, but it isn't. The function that calls common/common_linux.Virtualization() is fillFromStatWithContext() which is called by many process.Process methods in process_linux. We can't change private functions from the application side.

2020-09-11 16:11 UTC, Lomanic commented
In fact the call to `common.Virtualization()` (should be VirtualizationWithContext() probably also) comes from [common.BootTimeWithContext()](https://github.com/shirou/gopsutil/blob/8a625ec054ea912247e0372de6b2a02255a6c09b/internal/common/common_linux.go#L58) which is not cached anymore since #857. As I wrote in https://github.com/shirou/gopsutil/pull/857#issuecomment-629858607, moving to unix.Sysinfo would maybe remove this call.

I fear caching this will make it harder to run unit tests for this function (we would have to hook to this new variable `virtualizationCache` I think).

2020-09-12 05:45 UTC, shirou commented
ah, sorry for my misunderstanding. But as @Lomanic said, I also cache is not good for library. I will try to open a PR about using  `unix.Sysinfo`

2020-09-12 10:12 UTC, AtakanColak commented
@Lomanic #857 mention a device can start with wrong date but the question we must ask for this case is can a device start with wrong virtualization data? I don't think it can but of course we must be certain.

I'm not going to comment on unit tests as I'm not sure on potential effects of caching on unit tests.

2020-09-28 18:16 UTC, Lomanic requested changes

2020-09-28 18:55 UTC, Lomanic commented
I think maybe we should cache this value in fact, for unit tests we can work around this by resetting this internal variable to nil if we want to call Virtualization() more than once. This would really improve performances for process.Processes() (see https://github.com/shirou/gopsutil/issues/842#issuecomment-697026725)

2020-09-28 19:20 UTC, Lomanic commented
Here's a proper benchmarck

```bash
git -C "$(go env GOPATH)/src/github.com/shirou/gopsutil" checkout master
git -C "$(go env GOPATH)/src/github.com/shirou/gopsutil" reset --hard origin/master
git -C "$(go env GOPATH)/src/github.com/shirou/gopsutil" clean -f -d
cat <<EOF >> "$(go env GOPATH)/src/github.com/shirou/gopsutil/process/process_test.go"
func BenchmarkNewProcess(b *testing.B) {
	checkPid := os.Getpid()
	for i := 0; i < b.N; i++ {
		NewProcess(int32(checkPid))
    }
}
EOF
printf "\nBefore change:\n"
go test -bench=. github.com/shirou/gopsutil/process
curl -sL https://github.com/shirou/gopsutil/pull/942.diff | git apply
printf "\nAfter change:\n"
go test -bench=. github.com/shirou/gopsutil/process
```

Results are telling:
```
Before change:
goos: linux
goarch: amd64
pkg: github.com/shirou/gopsutil/process
BenchmarkNewProcess-4               2000            542412 ns/op
PASS
ok      github.com/shirou/gopsutil/process      3.106s

After change:
goos: linux
goarch: amd64
pkg: github.com/shirou/gopsutil/process
BenchmarkNewProcess-4              20000             78478 ns/op
PASS
ok      github.com/shirou/gopsutil/process      4.158s
```

2020-09-29 07:13 UTC, AtakanColak reviewed
removed explicit nil

2020-09-29 07:16 UTC, AtakanColak commented
@Lomanic removed explicit nil as requested. Thank you for benchmarking results. Looking forward for the merge.

2020-09-30 12:24 UTC, shirou approved these changes
As I said, I don't like cache in a library, but I don't have any other good solution, so I approve this PR. Thank you for your contribution!

2020-09-30 16:10 UTC, reimda commented
I tested this fix in telegraf and found that it makes performance similar to before #837 was merged.  Will this PR make it into a release soon?  We'd like to include it in telegraf 1.16.0 which is planned for next week.

2020-10-01 02:56 UTC, shirou commented
@Lomanic sorry for interrupting your comment, but I think your request is resolved. So I merge this PR. Thank you for your review and contribution!

2020-10-01 02:56 UTC, merged

2020-10-01 02:58 UTC, shirou commented
gopsutil is monthly release. After this PR merged, I have released `vv2.20.9`.