Fix Windows Ppid Cache Race Condition
shirou/gopsutil pull request #962
Opened 2020-10-12 08:39 UTC by AtakanColak

As per #961, a RWMutex to Process struct and thread-safe ppid access functions are added which are now used for windows but virtually can be used for other OSes in the future.  

Another solution would be to not cache at all, but this solution reduces overall system calls and in windows it makes quite the difference. 

Please do review. @Lomanic @shirou

2020-10-12 09:10 UTC, AtakanColak commented
go vet still fails, looking into it

2020-10-12 09:51 UTC, AtakanColak commented
go vet check passes after changing the mutex to a pointer that is initialized with NewProcess call

2020-10-13 08:27 UTC, AtakanColak commented
Squashed commits, waiting for review.

2020-10-15 22:54 UTC, Lomanic requested changes
Thanks for PR, I didn't yet have a chance to test it. See my comment.

2020-10-18 09:45 UTC, shirou commented
Sorry, #966 makes conflicts. But If you follow [the comment](https://github.com/shirou/gopsutil/pull/962/files#r503256996) and make the changes, this conflicts may resolved,

2020-10-21 12:01 UTC, AtakanColak commented
@Lomanic thank you for the doc link, seeing a caching in windows ppid showed me that I was right to start this feature beforehand. Resolved it by carrying the methods to process_windows.go

@shirou resolved the conflicts.

Even though my tests passed, please do test before merge.

2020-10-21 13:36 UTC, shirou commented
Thank you so much! I can reproduce race condition by using this test and this PR can fix.

```
% go test --race -v -run Test_Process_Ppid
```

```
func Test_Process_Ppid(t *testing.T) {
	wg := sync.WaitGroup{}
	testCount := 10
	p := testGetProcess()
	wg.Add(testCount)
	for i := 0; i < testCount; i++ {
		go func(j int) {
			ppid, err := p.Ppid()
			wg.Done()
			skipIfNotImplementedErr(t, err)
			if err != nil {
				t.Errorf("Ppid() failed, %v", err)
			}

			if j == 9 {
				t.Logf("Ppid(): %d", ppid)
			}
		}(i)
	}
	wg.Wait()
}
```

Could you replace the current `Test_Process_Ppid()` by this code, confirm, and commit again? Thanks!

2020-10-21 13:54 UTC, AtakanColak commented
@shirou test passed on my windows. Added to the commit.

2020-10-21 21:50 UTC, Lomanic commented
Problem with your test @shirou is that it doesn't test the same thing anymore (getting a non-zero value, and the same value as `os.Getppid()`). I would restore the previous one and put that one new test to a dedicated test like in [https://github.com/shirou/gopsutil/blob/master/disk/disk_test.go#L70-L85](https://github.com/shirou/gopsutil/blob/3202231bcdbd3a6d236dbcc3ec92a96ddfa7168f/disk/disk_test.go#L70-L85).

And I would also suggest to be explicit that this test is made to detect race conditions (in its name). This test could even be put in a new `process/process_race_test.go` with `// +build race` flag on top so it only runs when the race detector is enabled.

2020-10-22 01:10 UTC, shirou commented
Ah, yes, totally agree to @Lomanic . 

I'm really sorry but could you revert that commit and create a new `process/process_race_test.go` file? > @AtakanColak .

2020-10-23 08:39 UTC, AtakanColak commented
@Lomanic @shirou committed with a process_race_test.go instead.

2020-10-27 07:58 UTC, AtakanColak commented
@Lomanic could you review and merge if deemed sufficient please.

2020-10-29 19:52 UTC, merged